### ISSUE TITLE
some problems with shape

### ISSUE THREAD

**Issue by yingji425** [thauptmann/3D-ResNet-Builder-for-Keras#4]
Hi!
Thank you for sharing your code, which has so many options.
However, I met some problems.

When I directly download the dataset and run the demo. I got the following errors.
`ValueError: Dimensions must be equal, but are 8 and 16 for '{{node three_d_convolution_res_net/sequential_36/sequential_2/residual_conv_block_1/Add}} = Add[T=DT_HALF](three_d_convolution_res_net/sequential_36/sequential_2/residual_conv_block_1/sequential_13/sequential_12/batch_normalization_8/Cast_3, three_d_convolution_res_net/sequential_36/sequential_2/residual_conv_block_1/sequential_15/batch_normalization_10/Cast_3)' with input shapes: [?,?,8,8,128], [?,?,16,16,128].`

I thought maybe it is the problem with the input size.
So I used my own code with your ResNet architecture part. My input is size is [16 (frame), 112, 112, 3] (3 channels not 1 in your demo). with batchszie = 8.
However, this time it returned the following error: 

`tensorflow.python.framework.errors_impl.InvalidArgumentError: required broadcastable shapes at loc(unknown) [Op:Add]`

Then I get into the network part, I found in 'residual_conv_block_1', after calculating
```
intermediate_output = self.resnet_conv_block(inputs, training=training)
shortcut = self.shortcut_conv(inputs, training=training)
```
The shape of inputs is [8, 3, 27, 27, 64], the shape of intermediate_output is [8, 1, 7, 7, 128], the shape of shortcut is [8, 2, 14, 14, 128], so they can not be added `output_sum = tf.add(intermediate_output, shortcut)` here. 

Do you have any ideas about these problems?
I am sorry for my long issue.
Thank you very much.

**Comment by thauptmann** [comment]
Hello, 

no problem for the long post. I am happy that someone uses my library. That's probably a wrongly set stride or padding. I will check it out locally and and push an update when I fix it.

**Comment by thauptmann** [comment]
Hello again,

I fixed the problem. The stride of the second convolutional layer in a resnet block was falsely set to 2 sometimes. 
I tested all kernels and all depths without a problem, if you find another bug do not hesitate to write an issue.

Greetings

**Comment by yingji425** [comment]
Thank you for your quick response.
I also tested it and there is no problem now.
Thank you very much!

**Comment by yingji425** [comment]
Sorry again. I met a problem, and since it is not a bug in your code, so I didn't open a new issue.
Your network is built according to Class, so it can not be saved as 'h5' file or directly use the `model.save` to save the entire model right?(I will get an error when directly save the model `WARNING:absl:Found untraced functions such as re_lu_6_layer_call_and_return_conditional_losses, re_lu_6_layer_call_fn, re_lu_11_layer_call_and_return_conditional_losses, re_lu_11_layer_call_fn, re_lu_16_layer_call_and_return_conditional_losses while saving (showing 5 of 15). These functions will not be directly callable after loading.`) 
So I can save the weight only. But I am not familiar with this kind of subclassed model, I checked a lot, and still can not extract features from layers with your created model like this `features_layer1 = tf.keras.models.Model(
    inputs=model.inputs,
    outputs=model.get_layer(name="layer1").output,
)
`
because the model.layers show sequential not custom layers names.
So I wondered if it is possible to use your model to extract features. How can I get the output of other layers?
(I am sorry this maybe not be direct to your code's main purpose, so if you can help me I will be very happy, If it is not suitable to ask you here, I can delete this :) )
Thank you very much.

**Comment by thauptmann** [comment]
I read several threads on Github and Stackoverflow about that error message. As far as I understand it should not change the results of the network, maybe the runtime, but I am not sure about that. I could use model.save() and keras.models.load_model(model_path) just fine for the test data. 

Yeah, subclassing models complicates a lot of things in TensorFlow and I have not find the perfect way to do it. A master student of me used a similar model to extract the features after the global average layer. The trick is to get the layers of the model and call layers again on the sequential layer, e.g. model.layers[0].layers, to get a list of all layers, which the sequential layer contains.

**Comment by yingji425** [comment]
Hi! Thank you for your kind reply. It works. Now I can successfully extract features from inner layers.
