### ISSUE TITLE
3D ResNet for regression

### ISSUE THREAD

**Issue by DarylWM** [thauptmann/3D-ResNet-Builder-for-Keras#5]
Hello, and thank you for your work on this module.

I'm interested in training a 3D ResNet to predict a 3D image from a 2-channel 3D image, where input shape is (240, 240, 240, 2) and output shape is (240, 240, 240, 1). I'll probably need to add some dilated convolution layers to the model to preserve those dimensions, but I got stuck before that point.

I tried this to start with:
```
model = three_d_resnet_builder.build_three_d_resnet_50(input_shape= (240, 240, 240, 2), 
                                                       output_shape= (240, 240, 240, 1), 
                                                       output_activation='sigmoid', 
                                                       regularizer='l2',
                                                       squeeze_and_excitation=False, 
                                                       kernel_name='3D')

```
but get the exception:
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
`

I believe it is complaining about the output_shape not being an integer when it uses it to create a Dense layer in the [resnet_tail section](https://github.com/thauptmann/3D-ResNet-Builder-for-Keras/blob/238f43606eb04236dfdea8e79b2ddd18196d328c/three_d_resnet_builder/three_D_resnet.py#L52).

Is it possible to leave the output layers without a tail?

**Comment by thauptmann** [comment]
Dear DarylIWM,

I only used my module for classification and regression, that's why only a dense layer is possible. 
But your usage sounds also interesting. I have to think a little bit about how to implement it more adaptable. 
A Boolean to create the network without tail or replacing the dense layer depending on a string could be options. The Boolean Flag could be the easiest for the beginning.


Greetings

**Comment by thauptmann** [comment]
I added the variable _append_tail_ to _three_d_resnet_builder.build_three_d_resnet_50_ (and similar functions). If set to False it  returns the ResNet without an output layer and the network should return the flattened latent features.

**Comment by DarylWM** [comment]
Thanks Tony; I will give it a try.
